[build]
  command = "npm run build"
  publish = "dist/public"

[build.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"

# Configuração para Neon Database
# A variável DATABASE_URL já está configurada no Netlify
